from threading import local

# Create a thread-local storage object to hold request data
_request = local()


class CurrentUserMiddleware:
    """
    Middleware to store the current request in a thread-local variable.
    This allows access to the request and its users information globally
    within the current thread.
    """

    def __init__(self, get_response):
        """
        Initialize the middleware with the next middleware or view in the chain.

        Args:
            get_response (callable): The next middleware or view to be called.
        """
        self.get_response = get_response

    def __call__(self, request):
        """
        Store the current request in the thread-local variable and process the request.

        Args:
            request (HttpRequest): The current HTTP request object.

        Returns:
            HttpResponse: The response generated by the next middleware or view.
        """
        _request.value = request
        response = self.get_response(request)
        _request.value = None
        return response


def get_current_request():
    """
    Retrieve the current request stored in the thread-local variable.

    Returns:
        HttpRequest: The current HTTP request object, or None if not available.
    """
    return _request.value


def get_current_user():
    """
    Retrieve the current users from the stored request.

    Returns:
        User: The users associated with the current request, or None if not available.
    """
    request = get_current_request()
    if request:
        return request.user
    else:
        return None


def get_current_ip():
    """
    Retrieve the IP address of the client from the stored request.

    Returns:
        str: The IP address of the client, or None if not available.
    """
    request = get_current_request()
    if request:
        return request.META.get("REMOTE_ADDR")
    else:
        return None


def get_current_user_agent():
    """
    Retrieve the User-Agent header from the stored request.

    Returns:
        str: The User-Agent string of the client, or None if not available.
    """
    request = get_current_request()
    if request:
        return request.META.get("HTTP_USER_AGENT")
    else:
        return None
