# Generated by Django 4.2 on 2024-09-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="departament",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Administration"), (2, "Operations"), (3, "Human resources"), (4, "Finance"), (5, "Technology"), (6, "Legal / compliance"), (7, "Other")],
                null=True,
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="second_last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Second last name"
            ),
        ),
    ]
