# Generated by Django 4.2 on 2024-09-19 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_departament_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="action",
            field=models.CharField(max_length=255, verbose_name="Action"),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="change",
            field=models.TextField(verbose_name="Changes"),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, default=None, null=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="model",
            field=models.CharField(max_length=255, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="object_id",
            field=models.CharField(max_length=255, verbose_name="Object ID"),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="user_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Browser"
            ),
        ),
    ]
