# Generated by Django 4.2.16 on 2024-09-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userhistory_action_alter_userhistory_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departament',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'RAMIRO'), (2, 'CÉSAR'), (3, 'KARLA'), (4, 'HILDA')], null=True, verbose_name='Department'),
        ),
    ]
