# Generated by Django 4.2 on 2024-09-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportarExportar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_csv",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="temporal/imports",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import/Export",
                "verbose_name_plural": "Import/Export",
            },
        ),
    ]
