# Generated by Django 4.2 on 2024-09-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportAuthenticity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authenticity_chain", models.CharField(max_length=64)),
                ("report_name", models.CharField(max_length=255)),
                ("content", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Report Authenticity",
                "verbose_name_plural": "Report Authenticity Records",
            },
        ),
    ]
