"""
Django settings for EnterpriseApp project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import environ
from EnterpriseApp.utility_toolkit.system_variables import settings_variables


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# environ init
env = environ.Env()
# Read the local .env file when present. Environment secrets are recommended in production.
environ.Env.read_env(BASE_DIR / 'EnterpriseApp' / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me-only-for-local-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'data',
    'users',
    'reports',
    'imports',
    'api',
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'nested_admin',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'dal',
    'dal_select2',
]

# django_extensions/graph_models son herramientas de desarrollo.
# Load them only when installed to avoid breaking Docker or production.
try:
    import django_extensions  # noqa: F401
    THIRD_PARTY_APPS.append('django_extensions')
    GRAPH_MODELS = {
        'all_applications': True,
        'group_models': True,
    }
except ImportError:
    pass

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'EnterpriseApp.utility_toolkit.current_user_middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'EnterpriseApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EnterpriseApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# The development database
DB_ENGINE = env('DB_ENGINE', default=env('ENGINE', default='django.db.backends.sqlite3'))

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3-app',
        },
        'enterprise_data': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3-data',
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': env('DB_APP_NAME', default=env('APPDATA', default=env('NAME', default='enterprise_dms_appdata'))),
            'USER': env('DB_USER', default=env('USER_DB', default='')),
            'PASSWORD': env('DB_PASSWORD', default=env('PASSWORD', default='')),
            'HOST': env('DB_HOST', default=env('HOST', default='localhost')),
            'PORT': env('DB_PORT', default=env('PORT', default='3306')),
            'ATOMIC_REQUESTS': env.bool('ATOMIC_REQUEST', default=True),
        },
        'enterprise_data': {
            'ENGINE': DB_ENGINE,
            'NAME': env('DB_DATA_NAME', default=env('DB', default='enterprise_dms_database')),
            'USER': env('DB_USER', default=env('USER_DB', default='')),
            'PASSWORD': env('DB_PASSWORD', default=env('PASSWORD', default='')),
            'HOST': env('DB_HOST', default=env('HOST', default='localhost')),
            'PORT': env('DB_PORT', default=env('PORT', default='3306')),
            'ATOMIC_REQUESTS': env.bool('ATOMIC_REQUEST', default=True),
        },
    }

DATABASE_ROUTERS = [
    'data.router.DataRouter',
]

# Default User model for the app
AUTH_USER_MODEL = 'users.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PSWD_MODULE = "django.contrib.auth.password_validation."
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{AUTH_PSWD_MODULE}UserAttributeSimilarityValidator', },
    {'NAME': f'{AUTH_PSWD_MODULE}MinimumLengthValidator', },
    {'NAME': f'{AUTH_PSWD_MODULE}CommonPasswordValidator', },
    {'NAME': f'{AUTH_PSWD_MODULE}NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

COUNTRY = env('COUNTRY', default='mx')
REGION_SETTINGS = settings_variables['locales'][COUNTRY]
LANGUAGE_CODE = env('LANGUAGE_CODE', default=REGION_SETTINGS['country_info']['language_code'])
TIME_ZONE = env('TIME_ZONE', default=REGION_SETTINGS['country_info']['time_zone'])
USE_I18N = REGION_SETTINGS['i18n']['use_i18n']
USE_L10N = REGION_SETTINGS['i18n']['use_l10n']
USE_TZ = REGION_SETTINGS['i18n']['use_tz']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = '/usr/share/nginx/html'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# To redirect to home after login django admin
LOGIN_REDIRECT_URL = 'home'

# Group names with special permissions
REGISTER_ENABLED_GROUPS = ["Admin", "Superboss", "Manager"]

# To enable use iframes and django admin
X_FRAME_OPTIONS = 'SAMEORIGIN'

# to disable the check of the number of fields in a form
DATA_UPLOAD_MAX_NUMBER_FIELDS = env.int('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=10000)

# to use SMB
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:20001',
    'http://127.0.0.1:20001',
    'http://10.0.0.0',
    'http://10.0.0.0:20001',
    'http://10.1.0.0',
    'http://10.1.0.0:20001',
    'http://192.168.0.100:20001',
    'https://www.app.example.com',
    'https://app.example.com',
])

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'https://www.app.example.com',
    'https://app.example.com',
])

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_REFERRER_POLICY = 'same-origin'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('LOG_LEVEL', default='INFO'),
    },
}


# Django REST Framework: public API foundation for the future front-end.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': env.int('API_PAGE_SIZE', default=50),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
}

API_VERSION = 'v1'
